DVK-1323 - Link pilot routes to fairway card
finnishtransportagency/dvk pull request #923
Opened 2024-04-11 07:03 UTC by samkaariCGI

2024-04-15 06:43 UTC, nooksanen requested changes

2024-04-15 06:43 UTC, nooksanen commented on admin/src/components/form/fairwayCard/MainSection.tsx
> +            isLoading={!pilotRouteOptions}
Eikö isLoading olisi parempi ottaa isPending tms suoraan pilotroute-kyselystä? Nythän jos reittejä ei ole saatavilla, näyttää että olisi lataus kesken.

2024-04-15 06:43 UTC, nooksanen commented on cdk/lib/lambda/db/modelMapper.ts
> +      await cacheResponse(pilotRoutesCacheKey, data);
Onko cachessa nyt siis kaksi pilotRoutea joista toinen on "pilotRoutes" tyyppiä RtzData[] ja toinen on "pilotroutes" joka on FeatureCollection?

2024-04-16 09:41 UTC, samkaariCGI commented on admin/src/components/form/fairwayCard/MainSection.tsx
> +            isLoading={!pilotRouteOptions}
Käyttää isLoadingia nykyään kuten muutkin ylläpitoon liittyvät listat

2024-04-16 09:42 UTC, samkaariCGI commented on cdk/lib/lambda/db/modelMapper.ts
> +      await cacheResponse(pilotRoutesCacheKey, data);
Cachetus korjattu käyttämään oikeaa avainta ja tyyppiä.

2024-04-16 10:23 UTC, nooksanen approved these changes

2024-04-16 10:25 UTC, merged